title: Stuart Elimu
description: Inside Stue's Brain - Decoding Stuart Elimu
url: "https://stuartelimu.github.io/"
favicon: https://abs-0.twimg.com/emoji/v2/svg/1f9e0.svg

permalink: /:categories/:title
