title: Stuart Elimu
description: Inside Stue's Brain - Decoding Stuart Elimu
url: "https://stuartelimu.me"
favicon: https://abs-0.twimg.com/emoji/v2/svg/1f9e0.svg

twitter:
  username: stuartelimu
  card: summary_large_image

permalink: /:categories/:title

plugins:
  - jekyll-seo-tag
