title: Stuart Elimu
description: Inside Stue's Brain - Decoding Stuart Elimu
url: "https://stuartelimu.me"
favicon: https://img.icons8.com/ios-glyphs/30/1A1A1A/rubiks-cube.png

twitter:
  username: stuartelimu
  card: summary_large_image

permalink: /:categories/:title

plugins:
  - jekyll-seo-tag
